name: Build

on:
  pull_request:
    branches: ["master"]
    types: [opened, reopened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project true
        poetry install
    - name: Check docs
      run: poetry run gen-all
    - name: Typecheck
      run: poetry run pyright
    - name: Check formatting
      run: poetry run black --check .
    - name: Check isort
      run: poetry run isort --check-only . --profile black

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project true
        poetry install
    - name: Test
      run: |
        poetry run pytest -n 4
    - name: Build and install it on system host
      run: |
        poetry build
        pip install dist/pyetr-*.whl
        python build_runner.py
